[tool.poetry]
name = "game-app"
version = "0.1.0"
description = ""
authors = ["Sari <sarimarjaana@gmail.com>"]
readme = "README.md"
packages = [{include = "game_app"}]

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
